version: "{build}"

image: Visual Studio 2017

configuration:
 - Debug
 - Release

platform: Any CPU

clone_depth: 50

install:
 - cd %APPVEYOR_BUILD_FOLDER%
 - git submodule update --init --recursive

build:
 project: c:\projects\ci-sharp-test\ci-sharp-test.sln
 parallel: true

on_success:
 - set APP_FOLDER=%APPVEYOR_BUILD_FOLDER%\ci-sharp-test\Build\%CONFIGURATION%
 - if     "%APPVEYOR_REPO_TAG_NAME%" == "" set APP_ZIP=%APPVEYOR_PROJECT_NAME%.zip
 - if not "%APPVEYOR_REPO_TAG_NAME%" == "" set APP_ZIP=%APPVEYOR_PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%.zip
 - 7z a %APP_ZIP% %APP_FOLDER%\ci-sharp-test.exe* %APP_FOLDER%\*.dll
 - if "%CONFIGURATION%" == "Debug" 7z u %APP_ZIP% %APP_FOLDER%\*.pdb %APP_FOLDER%\*.xml
 - appveyor PushArtifact %APP_ZIP%
