version: "{build}"

image: Visual Studio 2017

configuration:
 - Debug
 - Release

platform: Any CPU

clone_depth: 50

install:
 - set
 - cd %APPVEYOR_BUILD_FOLDER%
 - git submodule update --init --recursive

build:
 project: c:\projects\ci-sharp-test\ci-sharp-test.sln
 parallel: true

before_deploy:
 - set
 - set ZipTag=%APPVEYOR_REPO_TAG_NAME%
 - if "%APPVEYOR_REPO_TAG_NAME%" == "" set ZipTag=%APPVEYOR_REPO_BRANCH%-%CONFIGURATION%
 - 7z a %APPVEYOR_PROJECT_NAME%-%ZipTag%.zip %APPVEYOR_BUILD_FOLDER%\Build\%CONFIGURATION%\*.exe
 - if "%CONFIGURATION%" == "Debug" 7z u %APPVEYOR_PROJECT_NAME%-%ZipTag%.zip %APPVEYOR_BUILD_FOLDER%\Build\%CONFIGURATION%\*.pdb
 - appveyor PushArtifact %APPVEYOR_PROJECT_NAME%-%ZipTag%.zip
