version: "{build}"

image: Visual Studio 2017

configuration:
 - Debug
 - Release

platform: Any CPU

clone_depth: 50

install:
 - set
 - cd %APPVEYOR_BUILD_FOLDER%
 - git submodule update --init --recursive

build:
 project: c:\projects\ci-sharp-test\ci-sharp-test.sln
 parallel: true

on_success:
 - set APP_ZIP_TAG=%APPVEYOR_REPO_TAG_NAME%
 - if "%APPVEYOR_REPO_TAG_NAME%" == "" set APP_ZIP_TAG=%APPVEYOR_REPO_BRANCH%-%CONFIGURATION%
 - set APP_ZIP=%APPVEYOR_PROJECT_NAME%-%APP_ZIP_TAG%.zip
 - 7z a %APP_ZIP% %APPVEYOR_BUILD_FOLDER%\ci-sharp-test\Build\%CONFIGURATION%\ci-sharp-test.exe*
 - if "%CONFIGURATION%" == "Debug" 7z u %APP_ZIP% %APPVEYOR_BUILD_FOLDER%\ci-sharp-test\Build\%CONFIGURATION%\*.pdb
 - appveyor PushArtifact %APP_ZIP%
 - dir
 - cd \
 - dir
